### ISSUE TITLE
version configuration produces weird error

### ISSUE THREAD

**Issue by mkorenkov** [bflad/chef-mysql_connector#6]
part of my role definition:

    ....
    "mysql_connector":
    {
        "j":
         {
             "install_paths": ["/var/lib/mysql_connector"],
              "version": "5.0.8"
         }
    },
    ....

For some reason, the archive name is generated with error: `mysql-connector-java-5.0.8/mysql-connector-java-5.1.28-bin.jar`

Exception information:

[2014-01-12T15:08:26+00:00] DEBUG: Mixlib::ShellOut::ShellCommandFailed: execute[mysql-connector-java-/opt/atlassian/jira/lib] (/tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql_connector/providers/j.rb line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of tar --strip-components=1 -xzf mysql-connector-java-5.1.28.tar.gz -C /opt/atlassian/jira/lib mysql-connector-java-5.0.8/mysql-connector-java-5.1.28-bin.jar ----
STDOUT: 
STDERR: tar: mysql-connector-java-5.0.8/mysql-connector-java-5.1.28-bin.jar: Not found in archive
tar: Exiting with failure status due to previous errors
---- End output of tar --strip-components=1 -xzf mysql-connector-java-5.1.28.tar.gz -C /opt/atlassian/jira/lib mysql-connector-java-5.0.8/mysql-connector-java-5.1.28-bin.jar ----
Ran tar --strip-components=1 -xzf mysql-connector-java-5.1.28.tar.gz -C /opt/atlassian/jira/lib mysql-connector-java-5.0.8/mysql-connector-java-5.1.28-bin.jar returned 2
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/mixlib-shellout-1.1.0/lib/mixlib/shellout.rb:248:in `invalid!'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/mixlib-shellout-1.1.0/lib/mixlib/shellout.rb:234:in `error!'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/shell_out.rb:36:in `shell_out!'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/provider/execute.rb:62:in `action_run'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/why_run.rb:63:in `call'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/why_run.rb:63:in `converge!'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/why_run.rb:61:in `each'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/mixin/why_run.rb:61:in `converge!'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/provider.rb:136:in `converge'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/provider.rb:125:in `run_action'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/resource.rb:593:in `run_action'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/runner.rb:49:in `run_action'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/runner.rb:81:in `converge'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/runner.rb:81:in `each'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/runner.rb:81:in `converge'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/runner.rb:80:in `converge'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/client.rb:378:in `converge'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/client.rb:420:in `do_run'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/client.rb:176:in `run'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/application/solo.rb:230:in `run_application'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/application/solo.rb:218:in `loop'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/application/solo.rb:218:in `run_application'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/../lib/chef/application.rb:70:in `run'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-10.14.2/bin/chef-solo:25
/opt/vagrant_ruby/bin/chef-solo:19:in `load'
/opt/vagrant_ruby/bin/chef-solo:19
[2014-01-12T15:08:26+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[mysql-connector-java-/opt/atlassian/jira/lib] (/tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql_connector/providers/j.rb line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of tar --strip-components=1 -xzf mysql-connector-java-5.1.28.tar.gz -C /opt/atlassian/jira/lib mysql-connector-java-5.0.8/mysql-connector-java-5.1.28-bin.jar ----
STDOUT: 
STDERR: tar: mysql-connector-java-5.0.8/mysql-connector-java-5.1.28-bin.jar: Not found in archive
tar: Exiting with failure status due to previous errors
---- End output of tar --strip-components=1 -xzf mysql-connector-java-5.1.28.tar.gz -C /opt/atlassian/jira/lib mysql-connector-java-5.0.8/mysql-connector-java-5.1.28-bin.jar ----
Ran tar --strip-components=1 -xzf mysql-connector-java-5.1.28.tar.gz -C /opt/atlassian/jira/lib mysql-connector-java-5.0.8/mysql-connector-java-5.1.28-bin.jar returned 2

**Comment by dwmarshall** [comment]
FWIW, I resolved this (temporarily) by copying the cookbook's `attributes/default.rb` to my own cookbook's `attributes/mysql_connector.rb` and the modified `version` there to get the outcome I wanted.

**Comment by bflad** [comment]
I've reworked the provider in 0.8.1 to correctly auto-detect many things now, which should fix this issue. Also added 5.0.8 checksum. Please let me know if its still causing trouble.
